{
"success": true,
"codes": "200",
"message": "",
"data": {
"data": [
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "【瑞银：港交所可以尝试号召伦交所股东召开临时大会】瑞银在9月16日的研报中表示，还不清楚香港交易所与伦敦证券交易所股东的直接接触进展将会如何，并注意到有报道称港交所可能还会调整要约，使其对伦交所的股东看起来更有吸引力。鉴于港交所的要约取决于伦交所终止收购Refinitiv的交易，港交所可以尝试说服伦交所股东召开临时大会，或要求推迟对伦交所/Refinitiv交易的投票；这两种方案都需要5%的股东支持。（新浪）",
"liveWallstreetnId": "20190917184941369100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568717391,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "沙特央行行长Ahmed Alkholifey：如果沙特阿美进入IPO阶段，各银行准备好满足其需求。",
"liveWallstreetnId": "20190917183803592100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716731,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "【 中国农科院畜禽良种化科研攻关计划取得多项成果 】 由中国农业科学院组织的畜禽良种化科研攻关计划实施以来取得了多项成果。据中国农科院相关负责人日前介绍，畜禽良种化科研计划致力于突破关键技术，改善我国肉牛、肉羊主导品种供种依赖进口的局面，提升肉鸡附加值和肉鸭市场占有率等。（新华社）",
"liveWallstreetnId": "20190917183825106100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716731,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "【华泰证券张继强团队：两因素致MLF利率未调降】9月17日，央行开展2000亿元MLF操作，利率保持不变。对此，华泰证券张继强团队指出，本次没有选择降低MLF利率可能有两点考量。一是降准刚刚落地，此时再降息容易让市场对政策和流动性产生过高的预期，也会对汇率造成压力；二是在LPR机制推广还刚刚开始，LPR合理利差还没有稳定前，调降MLF的带动作用有限，反而浪费一颗“子弹”。该团队指出，降准之后，本月20日LPR预计仍有调降空间。该团队强调，LPR机制预计会有三部曲：机制完善-机制推广-MLF调降引导下行。（中证网）",
"liveWallstreetnId": "20190917183718411100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716671,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "沙特央行行长Ahmed Alkholifey：现在评估石油设施袭击对预算的影响还为时尚早。",
"liveWallstreetnId": "20190917183354627100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716491,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "法国总统马克龙办公室官员：法国仍在等待英国方面提出详尽的脱欧提议。",
"liveWallstreetnId": "20190917183312606100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716431,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "机构调查：37名受访经济学家中，26人预计瑞士央行将于9月19日维持主要利率不变。",
"liveWallstreetnId": "20190917183211175100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716371,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "机构调查：预计瑞士央行将至少维持利率不变至2021年。",
"liveWallstreetnId": "20190917183240576100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716371,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
},
{
"id": null,
"deleted": false,
"version": null,
"published": null,
"liveTitle": "法国总s统马克龙办公室官员：法国目前还不能确定是否会达成脱欧协议。",
"liveWallstreetnId": "20190917182943128100",
"liveType": null,
"liveCreatetime": null,
"liveUpdatetime": null,
"channelSet": null,
"type": null,
"codeType": null,
"importance": "0",
"createdAt": 1568716191,
"updatedAt": null,
"commentStatus": null,
"star": null,
"new": true
}
]
},
"code": 200,
"obj": null
}
